// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kejaelgndmtragvcpstc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlamFlbGduZG10cmFndmNwc3RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDU4NDgsImV4cCI6MjA2NTY4MTg0OH0.5zJPesPl70RV6ezw7yFUQXHQhNmeBFnQjHI34o0CNkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);